version: '3.3'

services:
  node:
    container_name: tipsy_node
    image: node:latest
    working_dir: /home/node/app
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./src:/home/node/app
    links:
      - db
    networks:
      - tipsy_network
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'

  db:
    container_name: tipsy_mysql
    image: mysql:latest
    ports:
      - '3306:3306'
    networks:
      - tipsy_network
    env_file:
      - .env

  phpmyadmin:
    container_name: tipsy_phpmyadmin
    image: phpmyadmin:latest
    ports:
      - '8888:80'
    environment:
      - PMA_ARBITRARY=1

networks:
  tipsy_network:
    driver: bridge
